### ISSUE TITLE
Basic Example Project Request

### ISSUE THREAD

**Issue by SandeepanSengupta** [dpiegdon/tiny-temp-humidity-sensor#1]
Hi,

I am a newbie in MCU programming yet have ATTiny10 on shelf.
Is it possible to release example projects teaching features like Capacitive Touch Sensing (QTouch® Library) and PWM, as in One button LED controller with (debounced)double tap to switch to capacative touch sensing on same pin and driving LED using PWM

I know I'm asking a lot but I know nothing other than arduino

**Comment by dpiegdon** [comment]
I think this  http://ww1.microchip.com/downloads/en/DeviceDoc/Atmel-42326-Single-Key-Configurator-User-Guide_AT08801.pdf  is pretty much doing what you are asking for, except for the PWM, right?

**Comment by SandeepanSengupta** [comment]
Thank you for quick response @dpiegdon
I know nothing more than Arduino so I was looking something more like [this](https://github.com/technoblogy/attiny10core/issues/2)

**Comment by dpiegdon** [comment]
sorry, this is well beyond the scope of this project, and the time that I currenlty can spend. i have not used qtouch so far, so this probably would take me quite a bit of time.
